version: '2.2'
services:
  webui:
    build: webui
    ports:
      - 8082:80 
    volumes:
      - /webui/files/:/files:rw
  rng:
    build: rng
    ports:
      - '8080:80'
  hasher:
    build: hasher
    ports:
      - '8081:80'
  worker:
    build: worker

  redis:
    image: redis